spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    #servlet:
    #  path: .do
  server:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  db1:
    datasource:
      tomcat:
        validation-query: SELECT 1
        connection-properties: useUnicode=true;characterEncoding=utf-8;autoReconnection=true
        max-wait: 600000
        max-active: 50
        max-idle: 50
        min-idle: 8
        test-on-borrow: true
        test-while-idle: true
        validation-interval: 5000
      sql-script-encoding: UTF-8
  devtools:
    livereload:
      enabled: true

logging.config: classpath:logback.xml

server:
  port: 8081

attach.path: ${user.home}/uploads/adminkeys
