apiVersion: 1

# deleteDatasources:
#   -name: influxdb-flux

datasources:
  - name: influxdb-flux
    isDefault: true
    type: influxdb
    access: proxy
    url: http://localhost:8086
    user: admin
    secureJsonData:
      token: mytoken
      password: password
    jsonData:
      version: Flux
      organization: myorgname
      defaultBucket: mybucketname
