version : '3'
services : 
    web:
        build: .
        volumes:
            - was-logs:/usr/local/tomcat/logs
            - ${HOME}/uploads:/root/uploads
        ports:
            - "80:8080"
    
    ldap:
        image: osixia/openldap:latest
        hostname: ldap.hamonize.com        
        ports:            
            - "389:389"
            - "636:636"
        environment:
            HOSTNAME: ldap.hamonize.com
            LOG_LEVEL: 256
            LDAP_DOMAIN: hamonize.com
            LDAP_BASE_DN: dc=hamonize,dc=com
            LDAP_ADMIN_PASSWORD: admin
            LDAP_ORGANISATION: invesume
        volumes:
            - ldap-data:/var/lib/openldap
            - ./ldap/config:/etc/openldap/slapd.d              
        domainname: "ldap.hamonize.com"
        restart: always

    phpldapadmin:
        image: osixia/phpldapadmin:latest
        ports:
            - "8080:80"
        environment:
            - PHPLDAPADMIN_LDAP_HOSTS=ldap
            - PHPLDAPADMIN_HTTPS="false"
        links:
            - ldap
        depends_on:
            - ldap

    influxdb2:
        image: influxdb:2.0.4
        ports:
          - "8086:8086"
        volumes:
          - influxdb-storage:/var/lib/influxdb
        environment:
          - DOCKER_INFLUXDB_INIT_MODE=setup      
          - DOCKER_INFLUXDB_INIT_USERNAME=admin      
          - DOCKER_INFLUXDB_INIT_PASSWORD=password      
          - DOCKER_INFLUXDB_INIT_ORG=myorgname
          - DOCKER_INFLUXDB_INIT_BUCKET=mybucketname
          - DOCKER_INFLUXDB_INIT_RETENTION=1w
          - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken
    
    grafana:
        image: grafana/grafana:latest
        ports:
        - "3000:3000"
        volumes:
        - grafana:/var/lib/grafana
        - ./grafana/plugins:/var/lib/grafana/plugins
        - ./grafana.ini:/etc/grafana/grafana.ini          
volumes:
    hamonize_center.sql:
    psql-data:
    ldap-data:
    influxdb-storage:
    grafana:
    was-logs:
